[project]
name = "rpythong"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=45.0.4",
    "peewee>=3.18.1",
    "pygame>=2.6.1",
]
